### ISSUE TITLE
Is it possible to have some audio data of background noises?

### ISSUE THREAD

**Issue by sainimohit23** [axiom-data-science/OrcaCNN-data#2]
The positive and negative data provided here has variable length. I need some audio data of background noises. Then I will superimpose available data on background noises to get data of consistent length. It is required to train the RNN model.

**Comment by yosoyjay** [comment]
Yeah, for this project I guarantee that all of the sample we receive will be of variable length.  That's what it's like to work with real world data.

Fortunately there underlying data required for development of your RNN is there, you just need to munge the data into a formats that you need.
