### ISSUE TITLE
How many types of different pods or killer whale groups exist? And how do we differentiate between them? Do we have some sample data to visualize them?

### ISSUE THREAD

**Issue by ZER-0-NE** [axiom-data-science/OrcaCNN-data#3]

**Comment by yosoyjay** [comment]
The training data I provided actually includes different pods, I just mixed them together to create the "positive" and "negative" training sets.

This weekend I'll have some time to create a map that describes what each sample is.  That way you have more information about the samples and you maybe able to extend the models a bit.

**Comment by ZER-0-NE** [comment]
Yes. @yosoyjay
That would be wonderful.
